image:
  file: .gitpod.Dockerfile

tasks:
  - init: ./mvnw clean package && ./mvnw install -DskipTests=false
  - command: confluent local start

ports:
  - port: 8080

vscode:
  extensions:
    - Pivotal.vscode-spring-boot@1.22.0:NtlGb5ygHm2uP5qeqfVrCA==
    - cool2k.vscode-lombok@1.0.2:e816/wZO588Jp8PN58Wj6g==
    - Pivotal.vscode-boot-dev-pack@0.0.8:KGahbNlLCY19QUebUzdLbA==
